dist: xenial
language: go

go:
  - "1.10.x"
#  - 1.11.x

branches:
  only:
  - master
#  - sdlOnly

addons:
  apt:
    packages:
      - xvfb

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - go get github.com/kjx98/golib/to

script:
  - cd sdl
  - go build
  - go test
